services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: game-backend
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/gamedb?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./backend/target/classes:/app/target/classes

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: game-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: game-database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
